version : '3.7'
networks:
  hy-net:
    external: true
services:
  db:
        container_name : mysql
        hostname: mysql
        networks:
          hy-net:
        image: registry.cn-hangzhou.aliyuncs.com/trsrd/mysql:utf8mb4-5.7.26
        volumes:
           - /TRS/APP/mysql/mysql-data:/var/lib/mysql
           - /TRS/APP/mysql/conf.d:/etc/mysql/conf.d
           - /etc/localtime:/etc/localtime:ro
        ports :
                - 3306:3306
        restart: always
        environment:
          TZ: Asia/Shanghai
          MYSQL_ROOT_PASSWORD : "!QAZ2wsx1234"     #设置默认的root密码

